// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import * as path from "path";

// Load .env relative to this config file's directory (../../../.env)
// dotenv.config({ path: path.resolve(__dirname, "../../../.env") });
dotenv.config({path: path.resolve(process.cwd(), ".env")});
console.log(process.env.DATABASE_URL);
console.log(path.resolve(__dirname, "../../../.env"));

export default defineConfig({
  // Use paths relative to this config file
  schema: `prisma/schema.prisma`,
  migrations: {
    path: `prisma/migrations`,
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});

