// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";

// Load .env relative to this config file's directory (../../../.env)
if (process.env.NODE_ENV !== "production") {
  import("dotenv/config");
}
// dotenv.config({ path: path.resolve(process.cwd(), ".env") });

export default defineConfig({
  // Use paths relative to this config file
  schema: `prisma/schema.prisma`,
  migrations: {
    path: `prisma/migrations`,
  },
  datasource: {
    url: env("DATABASE_URL"),
    // url: "postgresql://fake:fake@localhost:5432/fake",
  },
});



