name: CI

on: 
  pull_request:
    branches: [ dev ]

permissions: 
  actions: read
  contents: read
  pull-requests: read

concurrency: 
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
  
jobs: 
  debug:
    name: Debug versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Print versions
        run: |
          node -v
          npm -v
          git status
          git branch --show-current

  # validate:
  #   name: Validate affected projects
  #   runs-on: ubuntu-latest

  #   strategy: 
  #     matrix: 
  #       node-version: [22, 24]

  #   env:
  #     NODE_ENV: test
    
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     with: 
  #       fetch-depth: 0

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with: 
  #       node-version: ${{ matrix.node-version }}
  #       cache: "npm"

  #   - name: Install dependencies
  #     run: npm ci
      
  #   - name: Set Nx base and head SHAs
  #     uses: nrwl/nx-set-shas@v5

  #   - name: Lint affected projects
  #     run: npx nx affected -t lint

  #   - name: Test affected projects
  #     run: npx nx affected -t test 

  #   - name: Generate Prisma Client
  #     run: npx prisma generate --schema=libs/backend/database/prisma/schema.prisma
  #     env:
  #       DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

  #   - name: Build affected projects
  #     run: npx nx affected -t build
      