name: CI

on: 
  pull_request:
    branches: [ dev ]

permissions: 
  actions: read
  contents: read
  pull-requests: read

concurrency: 
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
  
jobs: 
  validate:
    name: Validate affected projects
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [24]

    env:
      NODE_ENV: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with: 
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with: 
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Print versions
      run: |
        node -v
        npm -v
        git status
        git branch -a

    - name: Install dependencies
      run: npm ci
      
    - name: Set Nx base and head SHAs
      uses: nrwl/nx-set-shas@v5

    - name: Generate Prisma Client
      run: npx prisma generate --schema=libs/backend/database/prisma/schema.prisma
      env:
        DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

    - name: Lint affected projects
      run: npx nx affected -t lint

    # Will add the e2e test later
    - name: Test affected projects (Unit Tests only)
      run: npx nx test api --runInBand --silent

    - name: Cache Next.js build cache
      uses: actions/cache@v5
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('apps/web/**/*.[jt]s', 'apps/web/**/*.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-
 
    - name: Build affected projects
      run: npx nx affected -t build
      